"""Shared cached-AI-artifact infrastructure (summary + translation).

LumiRSS derives two cached artifacts from one provider call each — the
article summary (0015) and the article translation (0016). Both obey the
same money rules and the same honest-state contract, so the mechanics
live here exactly once:

Money rules (never drift between features):

- reading cache state NEVER calls the provider;
- a successful exact cache hit NEVER calls the provider again;
- only an explicit generation request (POST) may call the provider;
- duplicate simultaneous generations for the same identity are
  suppressed by an in-process per-key lock (single-process BFF) plus
  the DB UNIQUE identity.

Honest states: not_generated (no row) / generating / success / failed.
A stale ``generating`` row (the process died mid-call) is reported as
failed(interrupted) and can be regenerated by an explicit POST.

Domain modules (ai_summary, ai_translation) own only what is genuinely
theirs: cache-identity resolution from the article, prompt/provider
calls, their SQL statements (literal, fully parameterized — no runtime
value or identifier is ever interpolated), and the public state
dataclasses. The generate ORDER owned here is the compatibility
contract: mark generating → one provider call → persist failure
(delete on not-configured) or success → re-read the row.
"""

import asyncio
import hashlib
import re
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from datetime import UTC, datetime

from lumirss.ai_provider import (
    AiNotConfigured,
    AIProvider,
    AiProviderError,
)

STALE_GENERATING_SECONDS = 600
MAX_AI_INPUT_CHARS = 12000
_MAX_LOCKS = 256

STATUS_NOT_GENERATED = "not_generated"
STATUS_GENERATING = "generating"
STATUS_SUCCESS = "success"
STATUS_FAILED = "failed"

FAILURE_AUTH = "auth_error"
FAILURE_MODEL = "model_error"
FAILURE_RATE_LIMITED = "rate_limited"
FAILURE_TIMEOUT = "timeout"
FAILURE_INVALID_RESPONSE = "invalid_response"
FAILURE_UPSTREAM = "upstream_error"
FAILURE_INTERRUPTED = "interrupted"

AI_NOT_CONFIGURED_MESSAGE = (
    "AI is not configured. Set the API key on the server and "
    "configure a base URL and model in AI settings."
)


class AiContentUnavailable(Exception):
    """The article has no usable text content for the AI feature."""


def normalize_ai_content(
    text: str, *, max_chars: int = MAX_AI_INPUT_CHARS
) -> str:
    """Deterministic, bounded article text for hashing + the provider.

    Whitespace runs collapse to single spaces, then the text is
    truncated at ``max_chars`` — same input always produces the same
    hash, so the cache identity is stable.
    """
    collapsed = re.sub(r"\s+", " ", text).strip()
    return collapsed[:max_chars]


def content_hash(normalized_text: str) -> str:
    return hashlib.sha256(normalized_text.encode("utf-8")).hexdigest()


def provider_failure_type(exc: AiProviderError) -> str:
    from lumirss.ai_provider import (
        AiAuthError,
        AiInvalidResponse,
        AiModelError,
        AiRateLimited,
        AiTimeout,
    )

    if isinstance(exc, AiAuthError):
        return FAILURE_AUTH
    if isinstance(exc, AiModelError):
        return FAILURE_MODEL
    if isinstance(exc, AiRateLimited):
        return FAILURE_RATE_LIMITED
    if isinstance(exc, AiTimeout):
        return FAILURE_TIMEOUT
    if isinstance(exc, AiInvalidResponse):
        return FAILURE_INVALID_RESPONSE
    return FAILURE_UPSTREAM


def is_stale_generating(updated_at: str | None) -> bool:
    if updated_at is None:
        return True
    try:
        updated = datetime.fromisoformat(updated_at)
    except ValueError:
        return True
    age = (datetime.now(UTC) - updated).total_seconds()
    return age > STALE_GENERATING_SECONDS


def require_ai_configured(settings: dict[str, str]) -> None:
    """Raise the stable AiNotConfigured error unless base URL + model set."""
    from lumirss.ai_settings import KEY_BASE_URL, KEY_MODEL

    if not settings[KEY_BASE_URL] or not settings[KEY_MODEL]:
        raise AiNotConfigured(AI_NOT_CONFIGURED_MESSAGE)


class GenerationLockPool:
    """Bounded in-process lock pool keyed by any hashable key.

    Caps live locks at 256 and resets when exceeded: keys are derived
    from unbounded content refs, so unbounded key growth must not grow
    the dict forever. A reset can momentarily allow two generations of
    the same identity — the DB UNIQUE constraint still keeps the table
    honest.
    """

    def __init__(self) -> None:
        self._locks: dict[object, asyncio.Lock] = {}

    def lock_for(self, key: object) -> asyncio.Lock:
        lock = self._locks.get(key)
        if lock is None:
            if len(self._locks) >= _MAX_LOCKS:
                self._locks.clear()
            lock = asyncio.Lock()
            self._locks[key] = lock
        return lock


@dataclass(frozen=True)
class AiCacheIdentity:
    """Exact cache identity for one derived AI artifact row."""

    entry_ref: str
    content_hash: str
    provider: str
    model: str
    prompt_version: str
    language: str

    def row_params(self) -> tuple[str, str, str, str, str, str]:
        return (
            self.entry_ref,
            self.content_hash,
            self.provider,
            self.model,
            self.prompt_version,
            self.language,
        )


class CachedAiArtifactService:
    """Generate-and-cache state machine shared by summary + translation.

    Subclass contract — the domain parts only:

    - ``_resolve(entry_ref)`` → ``(input..., identity)`` from the live
      FreshRSS article + AI settings;
    - ``_call_provider(inputs, identity, settings)`` → the artifact
      payload values, ordered exactly as ``_persist_success`` expects
      (the ONLY provider call);
    - persistence hooks, each a literal parameterized statement against
      the artifact's own table: ``_fetch_row``, ``_mark_generating``,
      ``_mark_failed``, ``_persist_success``, ``_delete_identity_row``;
    - ``_state_from_row`` / ``_not_generated``: the public state
      dataclass mapping.

    Failure semantics owned here: a provider ``AiNotConfigured`` removes
    the transient generating row (a later GET then honestly reports
    not_generated); any other provider failure persists its stable
    failure type; both re-raise.
    """

    def __init__(
        self,
        db,
        adapter,
        settings_store,
        provider_factory: Callable[[str, str], Awaitable[AIProvider]],
    ) -> None:
        self._db = db
        self._adapter = adapter
        self._settings = settings_store
        self._provider_factory = provider_factory
        self._locks = GenerationLockPool()

    # -- public flows ----------------------------------------------------

    async def get(self, entry_ref: str):
        """Read-only state: NEVER calls the provider."""
        *_, identity = await self._resolve(entry_ref)
        row = await self._fetch_row(identity)
        if row is None:
            return self._not_generated(identity)
        return self._state_from_row(row, cached=True)

    async def generate(self, entry_ref: str):
        """Explicit generation: provider call only on a cache miss."""
        resolved = await self._resolve(entry_ref)
        inputs, identity = resolved[:-1], resolved[-1]
        row = await self._fetch_row(identity)
        if row is not None and row["status"] == STATUS_SUCCESS:
            return self._state_from_row(row, cached=True)
        async with self._locks.lock_for(identity.row_params()):
            row = await self._fetch_row(identity)
            if row is not None and row["status"] == STATUS_SUCCESS:
                return self._state_from_row(row, cached=True)
            return await self._generate(inputs, identity)

    # -- subclass hooks (domain-owned) ------------------------------------

    async def _resolve(self, entry_ref: str) -> tuple[object, ...]:
        raise NotImplementedError

    async def _call_provider(
        self,
        inputs: tuple[object, ...],
        identity: AiCacheIdentity,
        settings: dict[str, str],
    ) -> tuple[object, ...]:
        raise NotImplementedError

    def _state_from_row(self, row, *, cached: bool):
        raise NotImplementedError

    def _not_generated(self, identity: AiCacheIdentity):
        raise NotImplementedError

    # -- persistence hooks (subclass supplies literal SQL per table) ------

    async def _fetch_row(self, identity: AiCacheIdentity):
        raise NotImplementedError

    async def _mark_generating(self, identity: AiCacheIdentity) -> None:
        raise NotImplementedError

    async def _mark_failed(
        self, identity: AiCacheIdentity, failure_type: str
    ) -> None:
        raise NotImplementedError

    async def _persist_success(
        self, payload: tuple[object, ...], identity: AiCacheIdentity
    ) -> None:
        raise NotImplementedError

    async def _delete_identity_row(self, identity: AiCacheIdentity) -> None:
        raise NotImplementedError

    # -- shared state machine ---------------------------------------------

    async def _generate(
        self, inputs: tuple[object, ...], identity: AiCacheIdentity
    ):
        await self._db.migrate()
        settings = await self._settings.load()
        require_ai_configured(settings)
        await self._mark_generating(identity)
        try:
            payload = await self._call_provider(inputs, identity, settings)
        except AiProviderError as exc:
            if isinstance(exc, AiNotConfigured):
                # No provider state to keep: remove the transient row so a
                # later GET honestly reports not_generated.
                await self._delete_identity_row(identity)
            else:
                await self._mark_failed(
                    identity, provider_failure_type(exc)
                )
            raise
        await self._persist_success(payload, identity)
        row = await self._fetch_row(identity)
        assert row is not None  # just written
        return self._state_from_row(row, cached=False)
