"""Cached article summary domain (0015 Gate 4).

Pipeline:

    FreshRSS entry detail (contentText)
        → normalize (whitespace-collapse + deterministic bound)
        → contentHash (SHA-256 of the normalized text)
        → cache identity (entryRef, contentHash, provider, model,
                          promptVersion, language)
        → exact cache hit OR one provider call
        → persist success/failure metadata in lumi.sqlite

Honest states: not_generated (no row) / generating / success / failed.
A stale ``generating`` row (the process died mid-call) is reported as
failed(interrupted) and can be regenerated by an explicit POST.

Money rules:

- reading cache state NEVER calls the provider;
- a successful exact cache hit NEVER calls the provider again;
- only an explicit generation request (POST) may call the provider;
- duplicate simultaneous generations for the same identity are prevented
  by an in-process per-key lock (single-process BFF assumption) plus the
  DB UNIQUE identity.
"""

import asyncio
import hashlib
import re
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from datetime import datetime, timezone

from lumirss.ai_provider import (
    AIProvider,
    AiNotConfigured,
    AiProviderError,
    SUMMARY_PROMPT_VERSION,
)
from lumirss.ai_settings import (
    AiSettingsStore,
    KEY_BASE_URL,
    KEY_MODEL,
    KEY_PROVIDER,
    KEY_SUMMARY_LANGUAGE,
)
from lumirss.adapters.freshrss import FreshRSSAdapter
from lumirss.storage import Database

MAX_SUMMARY_INPUT_CHARS = 12000
STALE_GENERATING_SECONDS = 600

STATUS_NOT_GENERATED = "not_generated"
STATUS_GENERATING = "generating"
STATUS_SUCCESS = "success"
STATUS_FAILED = "failed"

FAILURE_AUTH = "auth_error"
FAILURE_MODEL = "model_error"
FAILURE_RATE_LIMITED = "rate_limited"
FAILURE_TIMEOUT = "timeout"
FAILURE_INVALID_RESPONSE = "invalid_response"
FAILURE_UPSTREAM = "upstream_error"
FAILURE_INTERRUPTED = "interrupted"

_MAX_LOCKS = 256


class AiContentUnavailable(Exception):
    """The article has no usable text content to summarize."""


@dataclass(frozen=True)
class CacheIdentity:
    entry_ref: str
    content_hash: str
    provider: str
    model: str
    prompt_version: str
    language: str

    def row_params(self) -> tuple[str, str, str, str, str, str]:
        return (
            self.entry_ref,
            self.content_hash,
            self.provider,
            self.model,
            self.prompt_version,
            self.language,
        )


@dataclass(frozen=True)
class SummaryState:
    status: str
    summary: str | None = None
    provider: str | None = None
    model: str | None = None
    prompt_version: str | None = None
    language: str | None = None
    generated_at: str | None = None
    failure_type: str | None = None
    cached: bool = False


def normalize_content(text: str) -> str:
    """Deterministic, bounded article text for hashing + the provider.

    Whitespace runs collapse to single spaces, then the text is truncated
    at MAX_SUMMARY_INPUT_CHARS — same input always produces the same hash.
    """
    collapsed = re.sub(r"\s+", " ", text).strip()
    return collapsed[:MAX_SUMMARY_INPUT_CHARS]


def content_hash(normalized_text: str) -> str:
    return hashlib.sha256(normalized_text.encode("utf-8")).hexdigest()


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _provider_failure_type(exc: AiProviderError) -> str:
    from lumirss.ai_provider import (
        AiAuthError,
        AiInvalidResponse,
        AiModelError,
        AiRateLimited,
        AiTimeout,
    )

    if isinstance(exc, AiAuthError):
        return FAILURE_AUTH
    if isinstance(exc, AiModelError):
        return FAILURE_MODEL
    if isinstance(exc, AiRateLimited):
        return FAILURE_RATE_LIMITED
    if isinstance(exc, AiTimeout):
        return FAILURE_TIMEOUT
    if isinstance(exc, AiInvalidResponse):
        return FAILURE_INVALID_RESPONSE
    return FAILURE_UPSTREAM


def _is_stale_generating(updated_at: str | None) -> bool:
    if updated_at is None:
        return True
    try:
        updated = datetime.fromisoformat(updated_at)
    except ValueError:
        return True
    age = (datetime.now(timezone.utc) - updated).total_seconds()
    return age > STALE_GENERATING_SECONDS


class SummaryService:
    """On-demand, cached article summarization."""

    def __init__(
        self,
        db: Database,
        adapter: FreshRSSAdapter,
        settings_store: AiSettingsStore,
        provider_factory: Callable[[str, str], Awaitable[AIProvider]],
    ) -> None:
        self._db = db
        self._adapter = adapter
        self._settings = settings_store
        self._provider_factory = provider_factory
        self._locks: dict[tuple, asyncio.Lock] = {}

    async def _resolve(self, entry_ref: str):
        from lumirss.entryref import decode_entry_ref

        item_id = decode_entry_ref(entry_ref)
        detail = await self._adapter.get_entry(item_id)
        normalized = normalize_content(detail.contentText)
        if not normalized:
            raise AiContentUnavailable(
                "This article has no text content to summarize."
            )
        settings = await self._settings.load()
        identity = CacheIdentity(
            entry_ref=entry_ref,
            content_hash=content_hash(normalized),
            provider=settings[KEY_PROVIDER],
            model=settings[KEY_MODEL],
            prompt_version=SUMMARY_PROMPT_VERSION,
            language=settings[KEY_SUMMARY_LANGUAGE],
        )
        return normalized, identity

    async def _fetch_row(self, identity: CacheIdentity):
        await self._db.migrate()
        return await self._db.fetch_one(
            "SELECT * FROM ai_summaries WHERE entry_ref = ? AND content_hash = ? "
            "AND provider = ? AND model = ? AND prompt_version = ? AND language = ?",
            identity.row_params(),
        )

    def _state_from_row(self, row, *, cached: bool) -> SummaryState:
        status = row["status"]
        if status == STATUS_GENERATING and _is_stale_generating(row["updated_at"]):
            return SummaryState(
                status=STATUS_FAILED,
                provider=row["provider"],
                model=row["model"],
                prompt_version=row["prompt_version"],
                language=row["language"],
                generated_at=None,
                failure_type=FAILURE_INTERRUPTED,
            )
        return SummaryState(
            status=status,
            summary=row["summary_text"] if status == STATUS_SUCCESS else None,
            provider=row["provider"],
            model=row["model"],
            prompt_version=row["prompt_version"],
            language=row["language"],
            generated_at=row["updated_at"] if status == STATUS_SUCCESS else None,
            failure_type=row["failure_type"] if status == STATUS_FAILED else None,
            cached=cached,
        )

    def _not_generated(self, identity: CacheIdentity) -> SummaryState:
        return SummaryState(
            status=STATUS_NOT_GENERATED,
            provider=identity.provider,
            model=identity.model,
            prompt_version=identity.prompt_version,
            language=identity.language,
        )

    async def get_summary(self, entry_ref: str) -> SummaryState:
        """Read-only state: NEVER calls the provider."""
        normalized, identity = await self._resolve(entry_ref)
        row = await self._fetch_row(identity)
        if row is None:
            return self._not_generated(identity)
        return self._state_from_row(row, cached=True)

    async def generate_summary(self, entry_ref: str) -> SummaryState:
        """Explicit generation: provider call only on a cache miss."""
        normalized, identity = await self._resolve(entry_ref)
        row = await self._fetch_row(identity)
        if row is not None and row["status"] == STATUS_SUCCESS:
            return self._state_from_row(row, cached=True)
        async with self._lock_for(identity):
            row = await self._fetch_row(identity)
            if row is not None and row["status"] == STATUS_SUCCESS:
                return self._state_from_row(row, cached=True)
            return await self._generate(normalized, identity)

    def _lock_for(self, identity: CacheIdentity) -> asyncio.Lock:
        key = identity.row_params()
        lock = self._locks.get(key)
        if lock is None:
            if len(self._locks) >= _MAX_LOCKS:
                self._locks.clear()
            lock = asyncio.Lock()
            self._locks[key] = lock
        return lock

    async def _generate(
        self, normalized: str, identity: CacheIdentity
    ) -> SummaryState:
        await self._db.migrate()
        settings = await self._settings.load()
        if not settings[KEY_BASE_URL] or not settings[KEY_MODEL]:
            raise AiNotConfigured(
                "AI is not configured. Set the API key on the server and "
                "configure a base URL and model in AI settings."
            )
        await self._db.execute(
            "INSERT INTO ai_summaries (entry_ref, content_hash, provider, model, "
            "prompt_version, language, status, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(entry_ref, content_hash, provider, model, prompt_version, language) "
            "DO UPDATE SET status = 'generating', failure_type = NULL, "
            "summary_text = NULL, updated_at = excluded.updated_at",
            (*identity.row_params(), STATUS_GENERATING, _utc_now(), _utc_now()),
        )
        provider = await self._provider_factory(
            settings[KEY_BASE_URL], settings[KEY_MODEL]
        )
        try:
            summary = await provider.summarize(
                text=normalized, language=identity.language
            )
        except AiProviderError as exc:
            if isinstance(exc, AiNotConfigured):
                # No provider state to keep: remove the transient row so a
                # later GET honestly reports not_generated.
                await self._db.execute(
                    "DELETE FROM ai_summaries WHERE entry_ref = ? AND content_hash = ? "
                    "AND provider = ? AND model = ? AND prompt_version = ? AND language = ?",
                    identity.row_params(),
                )
            else:
                await self._db.execute(
                    "UPDATE ai_summaries SET status = 'failed', failure_type = ?, "
                    "summary_text = NULL, updated_at = ? "
                    "WHERE entry_ref = ? AND content_hash = ? AND provider = ? "
                    "AND model = ? AND prompt_version = ? AND language = ?",
                    (
                        _provider_failure_type(exc),
                        _utc_now(),
                        *identity.row_params(),
                    ),
                )
            raise
        await self._db.execute(
            "UPDATE ai_summaries SET status = 'success', summary_text = ?, "
            "failure_type = NULL, updated_at = ? "
            "WHERE entry_ref = ? AND content_hash = ? AND provider = ? "
            "AND model = ? AND prompt_version = ? AND language = ?",
            (summary, _utc_now(), *identity.row_params()),
        )
        row = await self._fetch_row(identity)
        assert row is not None  # just written
        return self._state_from_row(row, cached=False)
